// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  describe("A keyboard shortcut map", function() {
    var map;
    map = void 0;
    beforeEach(function() {
      return map = new KeyboardShortcutMap();
    });
    it("maps a keyboard event to a command with certain arguments", function() {
      var ctrl1, args, command, _ref;
      ctrl1 = {
        ctrlKey: true,
        which: 49
      };
      _ref = map.getMappedCommand(ctrl1), command = _ref[0], args = _ref[1];
      expect(command).toBe('win');
      return expect(args).toEqual([1]);
    });
    it("returns an undefined command when the shortcut doesn't match any command", function() {
      var args, command, alt1, _ref;
      alt1 = {
        altKey: true,
        which: 49
      };
      _ref = map.getMappedCommand(alt1), command = _ref[0], args = _ref[1];
      return expect(command).not.toBeDefined();
    });
    it("maps Tab to a command when the input field is empty", function() {
      var args, command, tab, _ref;
      tab = {
        which: 9
      };
      _ref = map.getMappedCommand(tab, ""), command = _ref[0], args = _ref[1];
      return expect(command).toBeDefined();
    });
    return it("doesn't map Tab to a command when the input field isn't empty", function() {
      var args, command, tab, _ref;
      tab = {
        which: 9
      };
      _ref = map.getMappedCommand(tab, "user input"), command = _ref[0], args = _ref[1];
      return expect(command).not.toBeDefined();
    });
  });

}).call(this);
