// Generated by CoffeeScript 1.4.0
(function() {

  describe("A timer", function() {
    var currentTime, tick, timer;
    timer = currentTime = void 0;
    tick = function(time) {
      return currentTime += time;
    };
    beforeEach(function() {
      currentTime = 3498573498;
      timer = new Timer();
      return timer._getCurrentTime = function() {
        return currentTime;
      };
    });
    it("displays the elapsed time between two events", function() {
      var time;
      timer.start('run');
      tick(23894);
      time = timer.elapsed('run');
      expect(time).toBe(23894);
      tick(6);
      time = timer.finish('run');
      return expect(time).toBe(23900);
    });
    return it("clears previous entry when start is called multiple times", function() {
      var time;
      timer.start('run');
      tick(23894);
      timer.start('run');
      tick(26);
      time = timer.finish('run');
      return expect(time).toBe(26);
    });
  });

}).call(this);
