// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";
  var MockChat, exports, _ref,
    __slice = [].slice;

  var exports = (_ref = window.chat) != null ? _ref : window.chat = {};

  MockChat = (function() {

    function MockChat(irc) {
      var _this = this;
      irc.on('server', function(e) {
        switch (e.name) {
          case 'connect':
            return _this.onConnected();
          case 'disconnect':
            return _this.onDisconnected();
          case 'joined':
            return _this.onJoined.apply(_this, [e.context.channel].concat(__slice.call(e.args)));
          case 'names':
            return _this.onNames.apply(_this, [e.context.channel].concat(__slice.call(e.args)));
          case 'parted':
            return _this.onParted.apply(_this, [e.context.channel].concat(__slice.call(e.args)));
        }
      });
      irc.on('message', function(e) {
        return _this.onIRCMessage.apply(_this, [e.context.channel, e.name].concat(__slice.call(e.args)));
      });
    }

    MockChat.prototype.onConnected = function() {};

    MockChat.prototype.onDisconnected = function() {};

    MockChat.prototype.onIRCMessage = function() {};

    MockChat.prototype.onJoined = function() {};

    MockChat.prototype.onParted = function() {};

    return MockChat;

  })();

  exports.MockChat = MockChat;

}).call(this);
