// Generated by CoffeeScript 1.4.0
(function() {
  var DOM, exports, _ref;

  exports = (_ref = window.mocks) != null ? _ref : window.mocks = {};

  DOM = (function() {

    function DOM() {}

    DOM.prototype.generateHTML = function() {
      return this.html = $("<div id='templates'>\n\n  <div class='server-channels'>\n    <div class='server room'>\n      <div class='content-item'></div>\n    </div>\n    <ul class='channels'></ul>\n  </div>\n\n  <li class='channel room'>\n    <div class='content-item'></div>\n  </li>\n\n  <ul class='nicks'></ul>\n\n  <li class='nick'>\n    <div class='content-item'></div>\n  </li>\n\n  <ul class='messages'></ul>\n\n  <li class='message'>\n    <div class='source'></div>\n    <div class='content'></div>\n  </li>\n\n</div>\n\n<!-- main -->\n<div id='main'>\n  <div id='rooms-and-nicks' class='no-nicks'>\n    <div id='rooms-container'>\n      <h1>rooms</h1>\n      <div class='rooms'></div>\n    </div>\n    <div id='nicks-container'>\n      <h1>members</h1>\n    </div>\n  </div>\n\n  <div id='messages-and-input'>\n    <div id='notice'>\n      <div class='content'></div>\n      <button class='close'>X</button>\n      <button class='option2 hidden'></button>\n      <button class='option1 hidden'></button>\n    </div>\n    <div id='messages-container'></div>\n    <div id='status-and-input'>\n      <div id='status' class='content-item'></div>\n      <input id='input'></div>\n    </div>\n  </div>\n</div>");
    };

    DOM.prototype.setUp = function() {
      this.generateHTML();
      this.html.css('display', 'none');
      return $('body').append(this.html);
    };

    DOM.prototype.tearDown = function() {
      return this.html.remove();
    };

    return DOM;

  })();

  exports.dom = new DOM;

}).call(this);
