import sys
import os.path

prefix = """
##
# ** Auto-generated by src/script/prepackaged/prepackaged_scripts.py **
#
# To modify this file:
#   * create or edit a script (must be a .js file)
#   * put script in src/script/prepackaged/
#   * run 'make package-scripts'
#
# Maintains a list of the source code from scripts that come packaged with CIRC.
##

exports = window.script ?= {}

exports.prepackagedScripts = [

  "
"""

suffix = """
  "

]
"""

path = 'src/script/prepackaged/'

def isScript(filename):
    return filename[-3:] == '.js'

def getSourceArray():
    src = []
    for filename in os.listdir(path):
        if not isScript(filename): continue
        file = open(path+filename, 'r')
        content = file.read()
        file.close()
        content = content.replace('"', '\\"')
        src.append(content)
    return src

def createPackagedScriptsFile():
    file = open(path + 'source_array.coffee', 'w')
    source = getSourceArray()
    arrayContent = '\n  ",\n\n  "'.join(source)
    file.write(prefix + arrayContent + suffix)
    file.close()

createPackagedScriptsFile()
