
##
# ** Auto-generated by src/script/prepackaged/prepackaged_scripts.py **
#
# To modify this file:
#   * create or edit a script (must be a .js file)
#   * put script in src/script/prepackaged/
#   * run 'make package-scripts'
#
# Maintains a list of the source code from scripts that come packaged with CIRC.
##

exports = window.script ?= {}

exports.prepackagedScripts = [

  "

  "

]
