
##
# ** Auto-generated by src/script/prepackaged/prepackaged_scripts.py **
#
# To modify this file:
#   * create or edit a script (must be a .js file)
#   * put script in src/script/prepackaged/
#   * run 'make package-scripts'
#
# Maintains a list of the source code from scripts that come packaged with CIRC.
##

exports = window.script ?= {}

exports.prepackagedScripts = [

  "
setName('/dance');
setDescription('Type /dance have a Kirby dance');

send('hook_command', 'dance');

dance = \"(>'-')> <('-'<) ^(' - ')^ <('-'<) (>'-')>\";
onMessage = function(e) {
  send(e.context, 'command', 'say', dance);
  propagate(e, 'none');
};

  ",

  "setName('auto_identify');
setDescription('snoops /msg NickServ messages and automatically calls /msg NickServ identify <pw>');

send('hook_command', 'msg');
send('hook_message', 'privmsg');
loadFromStorage();

// Keeps track of the last NickServ password used in each server.
var serverPasswords = {};

var handleOutgoingMessage = function(context, words) {
  if (words.length != 3) { return; }
  if (words[0].toLowerCase() == 'nickserv' && words[1].toLowerCase() == 'identify') {
    serverPasswords[context.server] = words[2];
    saveToStorage(serverPasswords);
  }
};

var handleIncomingMessage = function(context, from, message) {
  if (from == 'NickServ' && message.indexOf('nickname is registered') >= 0) {
    pw = serverPasswords[context.server];
    send(context, 'message', 'notice', 'Automatically identifying nickname with NickServ...');
    send(context, 'command', 'raw', 'PRIVMSG', 'NickServ', '\"identify', pw + '\"');
  }
};

updatePasswords = function(loadedPasswords) {
  for (server in loadedPasswords) {
    if (!serverPasswords[server]) {
      serverPasswords[server] = loadedPasswords[server];
    }
  }
};

onMessage = function(e) {
  propagate(e);
  if (e.type == 'system' && e.name == 'loaded') {
    if (e.args[0]) {
      updatePasswords(e.args[0]);
    }
  } else if (e.type == 'command' && e.name == 'msg') {
    handleOutgoingMessage(e.context, e.args);
  } else if (e.type == 'message' && e.name == 'privmsg') {
    if (serverPasswords[e.context.server]) {
      handleIncomingMessage(e.context, e.args[0], e.args[1]);
    }
  }
};

  "

]
